/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZonesNewRouteImport } from './routes/zones_.new'
import { Route as ZonesZoneIdRouteImport } from './routes/zones_.$zoneId'
import { Route as NodesNodeIdRouteImport } from './routes/nodes_.$nodeId'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesNewRoute = ZonesNewRouteImport.update({
  id: '/zones_/new',
  path: '/zones/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesZoneIdRoute = ZonesZoneIdRouteImport.update({
  id: '/zones_/$zoneId',
  path: '/zones/$zoneId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/nodes_/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/certificates': typeof CertificatesRoute
  '/intelligence': typeof IntelligenceRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRoute
  '/schemas': typeof SchemasRoute
  '/zones': typeof ZonesRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/zones/new': typeof ZonesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/certificates': typeof CertificatesRoute
  '/intelligence': typeof IntelligenceRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRoute
  '/schemas': typeof SchemasRoute
  '/zones': typeof ZonesRoute
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/zones/$zoneId': typeof ZonesZoneIdRoute
  '/zones/new': typeof ZonesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/certificates': typeof CertificatesRoute
  '/intelligence': typeof IntelligenceRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/nodes': typeof NodesRoute
  '/schemas': typeof SchemasRoute
  '/zones': typeof ZonesRoute
  '/nodes_/$nodeId': typeof NodesNodeIdRoute
  '/zones_/$zoneId': typeof ZonesZoneIdRoute
  '/zones_/new': typeof ZonesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/certificates'
    | '/intelligence'
    | '/live'
    | '/login'
    | '/nodes'
    | '/schemas'
    | '/zones'
    | '/nodes/$nodeId'
    | '/zones/$zoneId'
    | '/zones/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/certificates'
    | '/intelligence'
    | '/live'
    | '/login'
    | '/nodes'
    | '/schemas'
    | '/zones'
    | '/nodes/$nodeId'
    | '/zones/$zoneId'
    | '/zones/new'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/certificates'
    | '/intelligence'
    | '/live'
    | '/login'
    | '/nodes'
    | '/schemas'
    | '/zones'
    | '/nodes_/$nodeId'
    | '/zones_/$zoneId'
    | '/zones_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  CertificatesRoute: typeof CertificatesRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  NodesRoute: typeof NodesRoute
  SchemasRoute: typeof SchemasRoute
  ZonesRoute: typeof ZonesRoute
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  ZonesZoneIdRoute: typeof ZonesZoneIdRoute
  ZonesNewRoute: typeof ZonesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones_/new': {
      id: '/zones_/new'
      path: '/zones/new'
      fullPath: '/zones/new'
      preLoaderRoute: typeof ZonesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones_/$zoneId': {
      id: '/zones_/$zoneId'
      path: '/zones/$zoneId'
      fullPath: '/zones/$zoneId'
      preLoaderRoute: typeof ZonesZoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes_/$nodeId': {
      id: '/nodes_/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  CertificatesRoute: CertificatesRoute,
  IntelligenceRoute: IntelligenceRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  NodesRoute: NodesRoute,
  SchemasRoute: SchemasRoute,
  ZonesRoute: ZonesRoute,
  NodesNodeIdRoute: NodesNodeIdRoute,
  ZonesZoneIdRoute: ZonesZoneIdRoute,
  ZonesNewRoute: ZonesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
