// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Veil.Zones.Infrastructure.Persistence;

#nullable disable

namespace Veil.Zones.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ZonesDbContext))]
    [Migration("20260717133659_ZoneWidget")]
    partial class ZoneWidget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("zones")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veil.Zones.Domain.Rule", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RateLimit")
                        .HasColumnType("jsonb")
                        .HasColumnName("rate_limit");

                    b.Property<long?>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("rules", "zones");
                });

            modelBuilder.Entity("Veil.Zones.Domain.Zone", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("CacheEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cache_enabled");

                    b.Property<string>("Challenge")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("challenge");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagedRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("managed_rules")
                        .HasDefaultValueSql("'{\"SqlInjection\":false,\"Xss\":false,\"PathTraversal\":false,\"InspectBody\":false,\"Action\":0}'::jsonb");

                    b.Property<bool>("Shadow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("shadow");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Upstream")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("upstream");

                    b.Property<string>("Widget")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("widget")
                        .HasDefaultValueSql("'{\"Enabled\":false,\"SiteKey\":\"\",\"Secret\":\"\",\"Theme\":\"auto\"}'::jsonb");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Hostname", "Veil.Zones.Domain.Zone.Hostname#Hostname", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("hostname");
                        });

                    b.HasKey("Id");

                    b.ToTable("zones", "zones");
                });

            modelBuilder.Entity("Wiaoj.Ddd.EntityFrameworkCore.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartitionKey", "ProcessedAt")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.HasIndex("ProcessedAt", "LockId", "LockExpiration")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("OutboxMessages", "zones");
                });

            modelBuilder.Entity("Veil.Zones.Domain.Rule", b =>
                {
                    b.HasOne("Veil.Zones.Domain.Zone", null)
                        .WithMany("Rules")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Veil.Zones.Domain.Zone", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
