<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ItemGroup">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Using" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="Include" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>